const USER_ROLES = {
  CLIENTE: 1,
  ASESOR: 2,
  LIDER: 3, 
  GERENTE: 4,
  ADMIN: 5,
  CONTADOR: 6,
  OWNER: 7
};

const ROLE_NAMES = {
  1: 'Cliente',
  2: 'Asesor', 
  3: 'Líder',
  4: 'Gerente',
  5: 'Admin',
  6: 'Contador',
  7: 'Owner'
};

const PERMISSIONS = {
  // Gestión de usuarios
  CREATE_USER: [USER_ROLES.ADMIN, USER_ROLES.OWNER],
  VIEW_ALL_USERS: [USER_ROLES.ADMIN, USER_ROLES.OWNER],
  VIEW_TEAM_USERS: [USER_ROLES.LIDER, USER_ROLES.GERENTE, USER_ROLES.ADMIN, USER_ROLES.OWNER],
  
  // Gestión de cotizaciones
  CREATE_QUOTE: [USER_ROLES.ASESOR, USER_ROLES.LIDER, USER_ROLES.GERENTE, USER_ROLES.ADMIN, USER_ROLES.OWNER],
  VIEW_ALL_QUOTES: [USER_ROLES.ADMIN, USER_ROLES.OWNER],
  VIEW_TEAM_QUOTES: [USER_ROLES.LIDER, USER_ROLES.GERENTE, USER_ROLES.ADMIN, USER_ROLES.OWNER],
  COMPLETE_QUOTE: [USER_ROLES.ADMIN, USER_ROLES.OWNER],
  APPROVE_QUOTE: [USER_ROLES.ADMIN, USER_ROLES.OWNER],
  
  // Gestión de contratos
  CREATE_CONTRACT: [USER_ROLES.ADMIN, USER_ROLES.OWNER],
  VIEW_ALL_CONTRACTS: [USER_ROLES.ADMIN, USER_ROLES.CONTADOR, USER_ROLES.OWNER],
  
  // Gestión de comisiones
  GENERATE_COMMISSION: [USER_ROLES.CONTADOR, USER_ROLES.OWNER],
  APPROVE_COMMISSION: [USER_ROLES.OWNER],
  VIEW_ALL_COMMISSIONS: [USER_ROLES.CONTADOR, USER_ROLES.OWNER]
};

module.exports = {
  USER_ROLES,
  ROLE_NAMES,
  PERMISSIONS
};