const {Router} = require("express")
const userRoutes = require("./userRoutes")
const packRoutes = require("./packRoutes")
const classRoutes = require("./classRoutes")
const promoRoutes = require("./promoRoutes")
const orderRoutes = require("./orderRoutes")
const popupRoutes= require("./popupRoutes")
const numberRoutes= require("./numberRoutes")
const asesoresCapacitaciones = require('./asesoresCapacitaciones')
const instagramVideoRoutes = require("./instagramVideoRoutes")
const carouselRoutes = require("./carouselRoutes")
const routes = Router()

routes
.use("/user", userRoutes)
.use("/pack", packRoutes)
.use("/class", classRoutes)
.use("/promo", promoRoutes)
.use("/order", orderRoutes)
.use("/popup", popupRoutes)
.use("/numbers", numberRoutes)
.use("/insta", instagramVideoRoutes)
.use("/asesores", asesoresCapacitaciones)
.use("/carousel", carouselRoutes)

module.exports = routes