const {Router} = require("express")
const userRoutes = require("./userRoutes")
const packRoutes = require("./packRoutes")
const classRoutes = require("./classRoutes")
const promoRoutes = require("./promoRoutes")
const orderRoutes = require("./orderRoutes")
const popupRoutes= require("./popupRoutes")
const numberRoutes= require("./numberRoutes")
const instagramVideoRoutes = require(("./instagramVideoRoutes"))
const carouselRoutes = require("./carouselRoutes")
const routes = Router()

routes
.use("/user", userRoutes)
.use("/pack", packRoutes)
.use("/class", classRoutes)
.use("/promo", promoRoutes)
.use("/order", orderRoutes)
.use("/popup", popupRoutes)
.use("/rifa", numberRoutes)
.use("number", numberRoutes)
.use("/insta", instagramVideoRoutes)
.use("/carousel", carouselRoutes)
module.exports = routes