// ============ QUOTE ACTIONS ============
export const CREATE_QUOTE_REQUEST = 'CREATE_QUOTE_REQUEST';
export const CREATE_QUOTE_SUCCESS = 'CREATE_QUOTE_SUCCESS';
export const CREATE_QUOTE_FAILURE = 'CREATE_QUOTE_FAILURE';

export const FETCH_QUOTES_REQUEST = 'FETCH_QUOTES_REQUEST';
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS';
export const FETCH_QUOTES_FAILURE = 'FETCH_QUOTES_FAILURE';

export const FETCH_QUOTE_REQUEST = 'FETCH_QUOTE_REQUEST';
export const FETCH_QUOTE_SUCCESS = 'FETCH_QUOTE_SUCCESS';
export const FETCH_QUOTE_FAILURE = 'FETCH_QUOTE_FAILURE';

export const UPDATE_QUOTE_REQUEST = 'UPDATE_QUOTE_REQUEST';
export const UPDATE_QUOTE_SUCCESS = 'UPDATE_QUOTE_SUCCESS';
export const UPDATE_QUOTE_FAILURE = 'UPDATE_QUOTE_FAILURE';

export const APPROVE_QUOTE_REQUEST = 'APPROVE_QUOTE_REQUEST';
export const APPROVE_QUOTE_SUCCESS = 'APPROVE_QUOTE_SUCCESS';
export const APPROVE_QUOTE_FAILURE = 'APPROVE_QUOTE_FAILURE';

export const REJECT_QUOTE_REQUEST = 'REJECT_QUOTE_REQUEST';
export const REJECT_QUOTE_SUCCESS = 'REJECT_QUOTE_SUCCESS';
export const REJECT_QUOTE_FAILURE = 'REJECT_QUOTE_FAILURE';

// ============ CONTRACT ACTIONS ============
export const CREATE_CONTRACT_REQUEST = 'CREATE_CONTRACT_REQUEST';
export const CREATE_CONTRACT_SUCCESS = 'CREATE_CONTRACT_SUCCESS';
export const CREATE_CONTRACT_FAILURE = 'CREATE_CONTRACT_FAILURE';

export const FETCH_CONTRACTS_REQUEST = 'FETCH_CONTRACTS_REQUEST';
export const FETCH_CONTRACTS_SUCCESS = 'FETCH_CONTRACTS_SUCCESS';
export const FETCH_CONTRACTS_FAILURE = 'FETCH_CONTRACTS_FAILURE';

export const FETCH_CONTRACT_REQUEST = 'FETCH_CONTRACT_REQUEST';
export const FETCH_CONTRACT_SUCCESS = 'FETCH_CONTRACT_SUCCESS';
export const FETCH_CONTRACT_FAILURE = 'FETCH_CONTRACT_FAILURE';

export const UPDATE_CONTRACT_REQUEST = 'UPDATE_CONTRACT_REQUEST';
export const UPDATE_CONTRACT_SUCCESS = 'UPDATE_CONTRACT_SUCCESS';
export const UPDATE_CONTRACT_FAILURE = 'UPDATE_CONTRACT_FAILURE';

export const SIGN_CONTRACT_REQUEST = 'SIGN_CONTRACT_REQUEST';
export const SIGN_CONTRACT_SUCCESS = 'SIGN_CONTRACT_SUCCESS';
export const SIGN_CONTRACT_FAILURE = 'SIGN_CONTRACT_FAILURE';

export const SEND_CONTRACT_REQUEST = 'SEND_CONTRACT_REQUEST';
export const SEND_CONTRACT_SUCCESS = 'SEND_CONTRACT_SUCCESS';
export const SEND_CONTRACT_FAILURE = 'SEND_CONTRACT_FAILURE';

// ============ PAYMENT ACTIONS ============
export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAILURE = 'CREATE_PAYMENT_FAILURE';

export const FETCH_PAYMENTS_REQUEST = 'FETCH_PAYMENTS_REQUEST';
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS';
export const FETCH_PAYMENTS_FAILURE = 'FETCH_PAYMENTS_FAILURE';

export const FETCH_PAYMENT_REQUEST = 'FETCH_PAYMENT_REQUEST';
export const FETCH_PAYMENT_SUCCESS = 'FETCH_PAYMENT_SUCCESS';
export const FETCH_PAYMENT_FAILURE = 'FETCH_PAYMENT_FAILURE';

export const VERIFY_PAYMENT_REQUEST = 'VERIFY_PAYMENT_REQUEST';
export const VERIFY_PAYMENT_SUCCESS = 'VERIFY_PAYMENT_SUCCESS';
export const VERIFY_PAYMENT_FAILURE = 'VERIFY_PAYMENT_FAILURE';

export const PROCESS_WOMPI_PAYMENT_REQUEST = 'PROCESS_WOMPI_PAYMENT_REQUEST';
export const PROCESS_WOMPI_PAYMENT_SUCCESS = 'PROCESS_WOMPI_PAYMENT_SUCCESS';
export const PROCESS_WOMPI_PAYMENT_FAILURE = 'PROCESS_WOMPI_PAYMENT_FAILURE';

// ============ COMMISSION ACTIONS ============
export const FETCH_COMMISSIONS_REQUEST = 'FETCH_COMMISSIONS_REQUEST';
export const FETCH_COMMISSIONS_SUCCESS = 'FETCH_COMMISSIONS_SUCCESS';
export const FETCH_COMMISSIONS_FAILURE = 'FETCH_COMMISSIONS_FAILURE';

export const GENERATE_COMMISSION_DOCUMENT_REQUEST = 'GENERATE_COMMISSION_DOCUMENT_REQUEST';
export const GENERATE_COMMISSION_DOCUMENT_SUCCESS = 'GENERATE_COMMISSION_DOCUMENT_SUCCESS';
export const GENERATE_COMMISSION_DOCUMENT_FAILURE = 'GENERATE_COMMISSION_DOCUMENT_FAILURE';

// ============ SUPPORT DOCUMENT ACTIONS ============
export const FETCH_SUPPORT_DOCUMENTS_REQUEST = 'FETCH_SUPPORT_DOCUMENTS_REQUEST';
export const FETCH_SUPPORT_DOCUMENTS_SUCCESS = 'FETCH_SUPPORT_DOCUMENTS_SUCCESS';
export const FETCH_SUPPORT_DOCUMENTS_FAILURE = 'FETCH_SUPPORT_DOCUMENTS_FAILURE';

export const APPROVE_SUPPORT_DOCUMENT_REQUEST = 'APPROVE_SUPPORT_DOCUMENT_REQUEST';
export const APPROVE_SUPPORT_DOCUMENT_SUCCESS = 'APPROVE_SUPPORT_DOCUMENT_SUCCESS';
export const APPROVE_SUPPORT_DOCUMENT_FAILURE = 'APPROVE_SUPPORT_DOCUMENT_FAILURE';

// ============ PACKAGE PURCHASE ACTIONS ============
export const CREATE_PACKAGE_PURCHASE_REQUEST = 'CREATE_PACKAGE_PURCHASE_REQUEST';
export const CREATE_PACKAGE_PURCHASE_SUCCESS = 'CREATE_PACKAGE_PURCHASE_SUCCESS';
export const CREATE_PACKAGE_PURCHASE_FAILURE = 'CREATE_PACKAGE_PURCHASE_FAILURE';

export const FETCH_PACKAGE_PURCHASES_REQUEST = 'FETCH_PACKAGE_PURCHASES_REQUEST';
export const FETCH_PACKAGE_PURCHASES_SUCCESS = 'FETCH_PACKAGE_PURCHASES_SUCCESS';
export const FETCH_PACKAGE_PURCHASES_FAILURE = 'FETCH_PACKAGE_PURCHASES_FAILURE';

// ============ DASHBOARD ACTIONS ============
export const FETCH_DASHBOARD_DATA_REQUEST = 'FETCH_DASHBOARD_DATA_REQUEST';
export const FETCH_DASHBOARD_DATA_SUCCESS = 'FETCH_DASHBOARD_DATA_SUCCESS';
export const FETCH_DASHBOARD_DATA_FAILURE = 'FETCH_DASHBOARD_DATA_FAILURE';

// ============ TEAM MANAGEMENT ACTIONS ============
export const FETCH_TEAM_MEMBERS_REQUEST = 'FETCH_TEAM_MEMBERS_REQUEST';
export const FETCH_TEAM_MEMBERS_SUCCESS = 'FETCH_TEAM_MEMBERS_SUCCESS';
export const FETCH_TEAM_MEMBERS_FAILURE = 'FETCH_TEAM_MEMBERS_FAILURE';

export const UPDATE_USER_HIERARCHY_REQUEST = 'UPDATE_USER_HIERARCHY_REQUEST';
export const UPDATE_USER_HIERARCHY_SUCCESS = 'UPDATE_USER_HIERARCHY_SUCCESS';
export const UPDATE_USER_HIERARCHY_FAILURE = 'UPDATE_USER_HIERARCHY_FAILURE';
