export const INFO_USERS = 'INFO_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER_BY_ID ='DELETE_USER_BY_ID'

export const FETCH_PACKS_REQUEST = 'FETCH_PACKS_REQUEST';
export const FETCH_PACKS_SUCCESS = 'FETCH_PACKS_SUCCESS';
export const FETCH_PACKS_FAILURE = 'FETCH_PACKS_FAILURE';

export const FETCH_PACK_REQUEST = 'FETCH_PACK_REQUEST';
export const FETCH_PACK_SUCCESS = 'FETCH_PACK_SUCCESS';
export const FETCH_PACK_FAILURE = 'FETCH_PACK_FAILURE';

export const CREATE_PACK_REQUEST = 'CREATE_PACK_REQUEST';
export const CREATE_PACK_SUCCESS = 'CREATE_PACK_SUCCESS';
export const CREATE_PACK_FAILURE = 'CREATE_PACK_FAILURE';

export const UPDATE_PACK_REQUEST = 'UPDATE_PACK_REQUEST';
export const UPDATE_PACK_SUCCESS = 'UPDATE_PACK_SUCCESS';
export const UPDATE_PACK_FAILURE = 'UPDATE_PACK_FAILURE';

export const DELETE_PACK_REQUEST = 'DELETE_PACK_REQUEST';
export const DELETE_PACK_SUCCESS = 'DELETE_PACK_SUCCESS';
export const DELETE_PACK_FAILURE = 'DELETE_PACK_FAILURE';

export const FETCH_YAPAYA_REQUEST = 'FETCH_YAPAYA_REQUEST';
export const FETCH_YAPAYA_SUCCESS = 'FETCH_YAPAYA_SUCCESS';  
export const FETCH_YAPAYA_FAILURE = 'FETCH_YAPAYA_FAILURE';

export const FETCH_ACTIVE_REQUEST = 'FETCH_ACTIVE_REQUEST' ; 
export const FETCH_ACTIVE_SUCCESS = 'FETCH_ACTIVE_SUCCESS' ;
export const FETCH_ACTIVE_FAILURE = 'FETCH_ACTIVE_FAILURE';

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL';

export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';

export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';



export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT' 
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS'
export const VERIFY_TOKEN_FAIL = 'VERIFY_TOKEN_FAIL'

export const FETCH_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';

export const REMOVE_VIDEO = 'REMOVE_VIDEO';

export const FETCH_CAPACITACIONES_REQUEST = 'FETCH_CAPACITACIONES_REQUEST';
export const FETCH_CAPACITACIONES_SUCCESS = 'FETCH_CAPACITACIONES_SUCCESS';
export const FETCH_CAPACITACIONES_FAILURE = 'FETCH_CAPACITACIONES_FAILURE';

export const REMOVE_CAPACITACION = 'REMOVE_CAPACITACION';

