export const INFO_USERS = 'INFO_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER_BY_ID ='DELETE_USER_BY_ID'

export const FETCH_PACKS_REQUEST = 'FETCH_PACKS_REQUEST';
export const FETCH_PACKS_SUCCESS = 'FETCH_PACKS_SUCCESS';
export const FETCH_PACKS_FAILURE = 'FETCH_PACKS_FAILURE';

export const FETCH_PACK_REQUEST = 'FETCH_PACK_REQUEST';
export const FETCH_PACK_SUCCESS = 'FETCH_PACK_SUCCESS';
export const FETCH_PACK_FAILURE = 'FETCH_PACK_FAILURE';

export const CREATE_PACK_REQUEST = 'CREATE_PACK_REQUEST';
export const CREATE_PACK_SUCCESS = 'CREATE_PACK_SUCCESS';
export const CREATE_PACK_FAILURE = 'CREATE_PACK_FAILURE';

export const UPDATE_PACK_REQUEST = 'UPDATE_PACK_REQUEST';
export const UPDATE_PACK_SUCCESS = 'UPDATE_PACK_SUCCESS';
export const UPDATE_PACK_FAILURE = 'UPDATE_PACK_FAILURE';

export const DELETE_PACK_REQUEST = 'DELETE_PACK_REQUEST';
export const DELETE_PACK_SUCCESS = 'DELETE_PACK_SUCCESS';
export const DELETE_PACK_FAILURE = 'DELETE_PACK_FAILURE';

export const FETCH_YAPAYA_REQUEST = 'FETCH_YAPAYA_REQUEST';
export const FETCH_YAPAYA_SUCCESS = 'FETCH_YAPAYA_SUCCESS';  
export const FETCH_YAPAYA_FAILURE = 'FETCH_YAPAYA_FAILURE';

export const FETCH_ACTIVE_REQUEST = 'FETCH_ACTIVE_REQUEST' ; 
export const FETCH_ACTIVE_SUCCESS = 'FETCH_ACTIVE_SUCCESS' ;
export const FETCH_ACTIVE_FAILURE = 'FETCH_ACTIVE_FAILURE';

export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS';
export const CREATE_RESERVATION_FAILURE = 'CREATE_RESERVATION_FAILURE';

export const FETCH_RESERVATIONS_SUCCESS = 'FETCH_RESERVATIONS_SUCCESS';
export const FETCH_RESERVATIONS_FAILURE = 'FETCH_RESERVATIONS_FAILURE';

export const FETCH_USER_RESERVATIONS_SUCCESS = 'FETCH_USER_RESERVATIONS_SUCCESS';
export const FETCH_USER_RESERVATIONS_FAILURE = 'FETCH_USER_RESERVATIONS_FAILURE';

export const UPDATE_RESERVATION_SUCCESS = 'UPDATE_RESERVATION_SUCCESS';
export const UPDATE_RESERVATION_FAILURE = 'UPDATE_RESERVATION_FAILURE';

export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS';
export const DELETE_RESERVATION_FAILURE = 'DELETE_RESERVATION_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT' 
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS'
export const VERIFY_TOKEN_FAIL = 'VERIFY_TOKEN_FAIL'
