export const INFO_USERS = 'INFO_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER_BY_ID ='DELETE_USER_BY_ID'

export const FETCH_PACKS_REQUEST = 'FETCH_PACKS_REQUEST';
export const FETCH_PACKS_SUCCESS = 'FETCH_PACKS_SUCCESS';
export const FETCH_PACKS_FAILURE = 'FETCH_PACKS_FAILURE';

export const FETCH_PACK_REQUEST = 'FETCH_PACK_REQUEST';
export const FETCH_PACK_SUCCESS = 'FETCH_PACK_SUCCESS';
export const FETCH_PACK_FAILURE = 'FETCH_PACK_FAILURE';

export const CREATE_PACK_REQUEST = 'CREATE_PACK_REQUEST';
export const CREATE_PACK_SUCCESS = 'CREATE_PACK_SUCCESS';
export const CREATE_PACK_FAILURE = 'CREATE_PACK_FAILURE';

export const UPDATE_PACK_REQUEST = 'UPDATE_PACK_REQUEST';
export const UPDATE_PACK_SUCCESS = 'UPDATE_PACK_SUCCESS';
export const UPDATE_PACK_FAILURE = 'UPDATE_PACK_FAILURE';

export const DELETE_PACK_REQUEST = 'DELETE_PACK_REQUEST';
export const DELETE_PACK_SUCCESS = 'DELETE_PACK_SUCCESS';
export const DELETE_PACK_FAILURE = 'DELETE_PACK_FAILURE';
